# This is a basic workflow to help you get started with Actions

name: Workflow_dispatch

# Controls when the workflow will run
on:
  
  # This is to allow Power apps to invoke the job from the app
  repository_dispatch:
    types: [invoke_workflow]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Configure:
    # The type of runner that the job will run on
    runs-on: [cts]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world! - New changes 
         

      - name: Configure
        shell: pwsh
        # run: echo ${env:GITHUB_WORKSPACE}
        run: echo "Configure"


      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   shell: pwsh
      #   run: |
      #     copy-item -recurse  ${env:GITHUB_WORKSPACE}\\Assets\\ -destination E:\Git_Actions_Dir -force
      #     echo ${{env.Git_Actions_Scripts_Dir}}
      #     set-location ${{env.Git_Actions_Scripts_Dir}}
      #     get-childitem .
      #     ./start-scheduled-task.ps1
      #   env:
      #       Git_Actions_Scripts_Dir: E:\Git_Actions_Dir\Assets\Scripts
  Prepare:

    runs-on: [cts]

    steps:
      - name: Prepare
        shell: pwsh
        run: echo "Prepare"

